uktrade/great-international-ui

core/templates/404.html
core/templates/core/includes/header_no_country_select.html

Don't show country on 404 page

---

README.md

Again something minor I stumbled upon – `directory-cms` refers to another host than the one that was in the README (https://github.com/uktrade/directory-cms/blob/898d264d44bf284a6e1ea0c79f64700ffe798f02/makefile#L66), and the `PORT` is set to 8012 in the makefile.
This is the only spot I could find where `int.trade.great` is used so I think updating it here is enough.

Update recommended host & port in README

---

core/tests/test_templates.py
core/tests/test_views.py

``page = dummy_page`` doesn't copy the underlying data so any subsequent mutation will also mutate the original ``dummy_page`` and leak into later tests.

Copy dummy_page before mutation

---

CHANGELOG.md
core/templates/core/uk_setup_guide/guide_landing_page.html

Fix image being squashed on guide landing page

---

CHANGELOG.md
core/templates/core/includes/hero_landing_page.html

Hotfix to merge straight into release.
fixes this issue on UAT 
to instead look like 
(which matches the current production appearance)

no ticket: Fix international hero image

---

CHANGELOG.md
core/templates/core/topic_list.html
core/templates/core/uk_setup_guide/guide_landing_page.html

Another quick hotfix for the hero images, this time on the topic and guide landing pages.

no ticket: Fix hero images for topic and guide listing pages.

---

CHANGELOG.md
core/helpers.py
core/tests/test_helpers.py

Fixing double filters showing up on isd page

---

CHANGELOG.md
core/templates/core/sector_page.html

Fixed about uk breadcrumb showing on industry page before page is ready

---

conf/url_redirects.py
conf/urls.py

no changelog as its just a fix to the previous commit.

Fix advanced engineering redirect failing if industries redirect is on.

---

CHANGELOG.md
find_a_supplier/forms.py
find_a_supplier/tests/conftest.py
find_a_supplier/tests/test_forms.py
find_a_supplier/tests/test_views.py
requirements.in
requirements.txt
requirements_test.txt

Updated find a supplier form with countries drop down to use the up-to-date countries and territories list from directory-constants.
- Directory constants library upgraded
Url to test: http://localhost:8012/international/trade/contact/
Before:
After:

Updated find a supplier form with countries drop down

---

CHANGELOG.md
euexit/forms.py
euexit/tests/test_forms.py
euexit/tests/test_views.py

Updated euexit form to use the up-to-date countries and territories list from directory-constants.
Effective change, drop down now includes territories including Hong Kong.
To test:
- Go to http://localhost:8012/international/brexit/contact/ (note view wasn't included in directory-cms fixtures so had to be manually set up)
- Check drop down includes territories such as Hong Kong
- Check all functionality works as before
After:

Update euexit form countries option to use countries and territories

---

CHANGELOG.md
core/forms.py

XOT-1266 add specific error messages to the campaign form

---

CHANGELOG.md
find_a_supplier/forms.py
find_a_supplier/redirects.py
find_a_supplier/templates/find_a_supplier/unsubscribe-failure.html
find_a_supplier/templates/find_a_supplier/unsubscribe-success.html
find_a_supplier/templates/find_a_supplier/unsubscribe.html
find_a_supplier/tests/test_redirects.py
find_a_supplier/tests/test_views.py
find_a_supplier/urls.py
find_a_supplier/views.py

We missed this when we copied from FAS to international

Add missing unsubscribe form

---

core/templates/core/companies/base-search.html

chrome does not support two value position-x: https://caniuse.com/#feat=mdn-css_properties_background-position-x_two_value_syntax
but calc is well supported:
https://caniuse.com/#feat=calc

Fix search icon position

---

.gitignore
CHANGELOG.md
core/templates/core/capital_invest/capital_invest_landing_page.html

As https://github.com/uktrade/directory-cms/pull/820 adds a new "Hero cta link" field to the Capital Investment homepage, this ticket is adding that link to the Hero button as you can see on the screenshot, the very bottom is showing the link when I hover the mouse over "Get in touch" button

Displays a CTA link on Capital Investment homepage hero

---

euexit/templates/euexit/form-contents.html

Changed from: 
https://www.great.gov.uk/content/invest/how-to-setup-in-the-uk/transition-period/ [Broken link]
to 
https://www.great.gov.uk/international/content/invest/how-to-setup-in-the-uk/transition-period/ [Live link]
https://uktrade.atlassian.net/browse/TT-2342

TT-2342 / Broken link change

---

CHANGELOG.md
core/forms.py
core/templates/core/investment_prospectus_form.html
core/templates/core/why_buy_from_the_uk_form.html
core/tests/test_forms.py
core/tests/test_views.py
core/views.py
locale/de/LC_MESSAGES/django.po
locale/es/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
locale/ja/LC_MESSAGES/django.po
locale/pt/LC_MESSAGES/django.po
locale/zh_Hans/LC_MESSAGES/django.po

Update the two forms below to replace country with market backed by the countries and territories list.
- BusinessEnvironmentGuideForm
- WhyBuyFromUKForm
------------------
------------------
-------------

TT-2372 : Switch country selectors to country and territory "markets"

---

CHANGELOG.md
core/templates/core/companies/base-case-study.html

Changed the markup structure to put the 'view' button in its own grid at the end - so now tabs go down the page properly - and on small screens, the button goes below the contact details.

GAA-18_column_structure_case_study

---

CHANGELOG.md
core/templates/captcha/includes/js_v3.html

Change captcha implementation so that the challenge token is created only as the form is submitted rather than on load. This removes the potential for the token to expire before submission.

GBAU-918 Fix reCaptcha timeout

---

CHANGELOG.md
requirements.in
requirements.txt
requirements_test.in
requirements_test.txt

* Django to 2.2.21
* py to at least 1.10.0
NOTICKET: upgrade py dependency, too

NOTICKET: Upgrade dependencies

---

requirements.in
requirements.txt
requirements_test.txt

NOTICKET: Bump django to 2.2.22 (security update)

---

CHANGELOG.md
conf/settings.py
core/middleware.py
core/tests/test_middleware.py

Personal Identifiable Information (PII) in the form of email addresses is injected into links by Outlook as values to a `data` parameter.
These 'safe links' don't appear to have a consistent pattern, a small sample data available looks like:
- `/international/content/opportunities/<https://eur02..safelinks.protection.outlook.com/?url=[url]&data=[PII]&sdata=[sdata]&reserved=0`
- `/international/trade/<https://eur02.safelinks.protection.outlook.com/?url=[url]&data=[PII]&sdata=[sdata]&reserved=0`
- `/international/?amp;data=[PII]&amp;sdata=[sdata]&amp;reserved=0&lang=en-gb`
- `/international/?lang=zh-hans<https://eur02.safelinks.protection.outlook.com/?url=[url]?lang=zh-hans&data=[PII]&sdata=[sdata]&reserved=0`
- `/international/invest/<https://eur02.safelinks.protection.outlook.com/?url=[url …

Remove MS Defender Safe Links from client requests

---

CHANGELOG.md
conf/urls.py
core/header_config/nav_tree.py
find_a_supplier/templates/find_a_supplier/landing_page.html
find_a_supplier/tests/test_templates.py

This changeset removes the Sector/Industry panel from the Find A Supplier page, as requested by the content team.
It also adds in a sub-nav (black strip) for the sibling pages in the Buy From the UK section we're retaining.

GP2-3375: Remove sectors list from Find-A-Supplier search page

---

CHANGELOG.md
core/templates/core/contact_international_triage.html

NOTICKET: Remove now-redundant back link from contact triage page

---

CHANGELOG.md
conf/tests/test_redirects.py
conf/urls.py
core/constants.py

Make FDI form path match that of page in CMS so that when you "view live" from the CMS you end up on the actual page, not a broken one.
Also delete unneeded serializer mapping to the fdi templates -- they are directly mapped in urls.py before the magic catchall route is triggered

GP2-3407: Make FDI form path match that of page in CMS

---

CHANGELOG.md
investment_atlas/templates/investment_atlas/region.html

This follows a pattern set for Success Stories on other pages and also the Find A Supplier CTA markup

 NOTICKET - Add support for case studies to Region detail page

---

investment_atlas/helpers.py
investment_atlas/tests/test_helpers.py

Prevents a template error when a blank sector is selected. Related sector label logic is now fully resilient.

Fix error when blank related sector selected

---

CHANGELOG.md
core/templates/core/base.html

Adds the Bing Webmaster Tools site verification as meta tag to all pages under /international/.

Add Bing Webmaster Tools meta tag

---

contact/templates/contact/base.html
core/templates/core/base.html
core/templates/core/base_cms.html
second_qualification/templates/second_qualification/base.html

Bing `<meta>` tag was not showing on most pages as the `head_other` template block was being overridden. This fix ensures the base block is called first.

Ensure `head_other` block calls ancestor

---

CHANGELOG.md
investment_atlas/templates/investment_atlas/opportunity_listing_page.html
investment_atlas/templates/investment_atlas/region.html
investment_atlas/templates/investment_atlas/sector.html
investment_atlas/templatetags/atlas_tags.py
investment_atlas/tests/test_templatetags.py
investment_atlas/tests/test_views.py
investment_atlas/views.py

Adds the ability to show investment opportunities results filtered by region or sector even when investment type has not been selected. Links to investment opportunities on region and sector pages now specify the relevant region or sector.

GLS-220/221 link to filtered results

---

CHANGELOG.md
investment_atlas/templates/investment_atlas/includes/svg/regions-map.svg.html

This PR updates the viewbox of the UK regions SVG map so that the Shetland islands are no longer hidden.
**Screenshot before**
**Screenshot after**

Show Shetland Islands on regions map

---

CHANGELOG.md
requirements.in
requirements.txt
requirements_test.txt

This PR upgrades the `elastic-apm` package to version 6, as version 5 is incompatible with python3.9 ([docs here](https://www.elastic.co/guide/en/apm/agent/python/5.x/supported-technologies.html)). 

Upgrade elastic-apm to version 6

---

CHANGELOG.md
requirements.in
requirements.txt
requirements_test.txt

This PR upgrades the `Whitenoise` package in order to fix an issue in which javascript and css files are not decompressed when accessing the site in Safari.
The issue comes from using Django version 3.x with Whitenoise < 5 ([issue details here](https://code.djangoproject.com/ticket/31082)).
**Testing locally**
The issue only appears in the live environments, but I have deployed this branch to dev & staging to test and it has been successful.

Upgrade whitenoise to 6.2.0

---

CHANGELOG.md
requirements.in
requirements.txt
requirements_test.txt

This PR upgrades django to version `3.2.16` and directory-validators to `9.2.1` which supports this newer version of django.

Upgrade to django 3.2.16

---

CHANGELOG.md

This PR upgrades the changelog to include the last 2 releases.

Upgrade changelog with versions 4.1.1-4.1.2

---

requirements.in
requirements.txt
requirements_test.txt

Upgrades requests to 2.31.0 and adds an additional dependancy to django-oauth-toolkit to fix compatibility with Django 4.1.9

Upgraded requests to 2.31.0

---

requirements.in
requirements.txt
requirements_test.txt

Bump Cryptography to 41.0.7 and directory-* deps to latest versions

Bump Cryptography to 41.0.7 and directory-* deps to latest versions

---

investment_atlas/templates/investment_atlas/includes/hero_image.html

Issue observed with some hero videos not displaying/playing
A typo fix in a previous release seems to have corrected the typo but brought about an issue where the video source type value should be prefixed with `video/`. The typo meant that previously no source type was rendered so its probable that the browser did the gap fill.

Bug fix issue with hero video source type attribute value

---

core/templates/atlas/components/footer.html

Pointing contact us footer link to great-cms international contact form instead of EYB
N/A

Pointing contact us footer link to great-cms international contact form instead of EYB

---

core/templates/atlas/components/footer.html

Accessibility link added to international footer and updated contact us link text to help using this site
N/A

Accessibility link added to international footer and updated contact us link text to help using this site

---

core/templates/atlas/components/footer.html

To fit with recent changes on domestic, this change is to update the footer links to have a link to the cookies settings page and change the "privacy and cookies" link label to "privacy".

GRTLV-53 - Add cookies link to footer and change privacy label

---

core/templates/core/base.html

This ticket fixes the missing 'http / https' in the Xlang selection.

FIXED https error in xlang selection

---

core/templates/core/base.html

This ticket removed the hreflang tag injection.

Remove hreflang tag injection
