uktrade/great-international-ui

.circleci/config.yml, manifest.yml, runtime.txt
Reverts uktrade/great-international-ui#2
=> Lock build pack

conf/urls.py, core/mixins.py, core/templates/core/article_list.html, core/templates/core/article_related_content_cards.html, core/templates/core/article_related_content_list.html, core/templates/core/campaign.html, core/templatetags/cms_tags.py, core/templatetags/tests/test_templatetags.py, core/tests/test_views.py, core/views.py, requirements.in, requirements.txt, requirements_test.txt
https://uktrade.atlassian.net/browse/CMS-703
=> Add article list pages

core/mixins.py, core/tests/test_views.py, core/views.py
=> Set page_type for homepage

core/templates/core/landing_page.html, core/tests/test_views.py
https://uktrade.atlassian.net/browse/CMS-898
=> Add related pages to homepage

core/templates/core/sector_page.html, requirements.in, requirements.txt, requirements_test.txt
=> Update statistics to show number first

conf/urls.py, core/mixins.py, core/tests/test_views.py
Can you be very thorough with this PR? I would not be surprised if there are entire features which I'm meant to do as part of this that I haven't stumbled across.
=> CMS-1168 — Enable i18n and l10n

conf/settings.py
=> Enable feature flag for "how to do business in the uk"

CHANGELOG.md, core/templates/core/base_cms.html
https://uktrade.atlassian.net/browse/CMS-775
=> Add alternate language urls to metadata

requirements.in, requirements.txt, requirements_test.txt
No changelog because it's a bugfix for a pre-release enhancement.
=> CI-145 Update invest header

CHANGELOG.md, core/static/js/dit.tagging.js, core/templates/core/capital_invest/capital_invest_opportunity_page.html, core/templates/core/includes/opportunity_card.html, core/templates/core/sector_page.html
=> Ci 196 redesign of similar opportunities card

CHANGELOG.md
=> 2019.07.08 release changelog update

CHANGELOG.md, core/templates/core/sector_page.html, core/tests/test_views.py, core/views.py
=> Ci 325 randomise ci projects on sector page

CHANGELOG.md, core/helpers.py, core/views.py, euexit/views.py, perfect_fit_prospectus/views.py
=> CI-303: Update international Header

CHANGELOG.md, package.json, yarn.lock
=> Update JS dev dependencies to fix security alerts.

core/helpers.py, core/templates/core/capital_invest/capital_invest_opportunity_listing_page.html, core/tests/test_helpers.py, core/tests/test_views.py, core/views.py
No changelog as this is adding to a ticket and bulk change already on there from pr before
=> Ci 324 capital invest sub sectors

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.txt
=> Updated requirements to fix pagination bug

CHANGELOG.md, core/templates/core/about_dit/services_page.html, core/templates/core/about_uk/why_choose_the_uk_page.html
=> Change "Contact Us" section on services page in "About DIT" to markdown

CHANGELOG.md, core/sass/main.css, core/templates/core/includes/card_with_publish_date.html
=> Moved extends tag to be first on page to fix error

core/templates/core/capital_invest/capital_invest_region_page.html, core/tests/test_views.py, core/views.py
Updated logic that I missed in previous pr
=> Missed showing accordions logic added

core/templates/core/capital_invest/capital_invest_region_page.html
Did look like:
Now looks like:
=> Ci 367 update region pages

core/templates/core/base.html, core/views.py, makefile, requirements.in, requirements.txt, requirements_test.txt
Also remove the 'current_header_section' underline in the short term.
=> CI-303: Update header to latest version

CHANGELOG.md, core/constants.py, perfect_fit_prospectus/urls.py, perfect_fit_prospectus/views.py
=> Add GA360 data to perfect fit

CHANGELOG.md, core/templates/core/about_dit/services_page.html
=> Fixed how we help issue on internet explorer

CHANGELOG.md, core/templates/core/about_uk/why_choose_the_uk_page.html
=> Update styling on ebooks promotional section

CHANGELOG.md, core/tests/test_views.py, core/views.py, invest/templates/invest/landing_page.html
=> Ci 353 use focal area on invest home page

CHANGELOG.md, core/templates/core/about_dit/about_dit_landing_page.html, core/templates/core/about_dit/services_page.html, core/templates/core/article_related_content_cards.html, core/templates/core/capital_invest/capital_invest_landing_page.html, core/templates/core/capital_invest/capital_invest_opportunity_page.html, core/templates/core/how_to_do_business_landing_page.html, core/templates/core/includes/featured_article_card.html, core/templates/core/landing_page.html, core/templates/core/sector_page.html, core/templates/core/topic_list.html, core/templates/core/uk_setup_guide/guide_landing_page.html, invest/templates/invest/hpo/high_potential_opportunity_detail.html, invest/templates/invest/landing_page.html
=> Commonised responsive pattern on all places using column-third

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.txt
=> CI-422: Update Django Version

CHANGELOG.md, invest/redirects.py, invest/tests/test_views.py
=> Change hpo contact form redirects

CHANGELOG.md, core/templates/core/about_uk/why_choose_the_uk_page.html
=> Uses pdf doc for ebook section on why choose uk page

CHANGELOG.md, core/forms.py, core/templates/core/capital_invest/capital_invest_contact_form.html, core/templates/core/capital_invest/capital_invest_contact_form_success.html, core/tests/test_forms.py
=> Given help text to form and added company name as optional field

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.txt
=> CI-424: Disable Lazy Loading of images.

CHANGELOG.md, core/templates/core/companies/base-profile.html
=> GTRANSFORM-349 add external link attributes

core/templates/core/capital_invest/capital_invest_region_page.html
=> Fixed comment

CHANGELOG.md, find_a_supplier/redirects.py, find_a_supplier/tests/test_views.py
=> FAS contact redirect

CHANGELOG.md, find_a_supplier/templates/find_a_supplier/landing_page.html
=> Fix FAS search term

CHANGELOG.md, investment_support_directory/templates/investment_support_directory/contact.html
=> Fix ISD company contact breadcrumbs

CHANGELOG.md, core/templates/core/article_related_content_list.html, find_a_supplier/redirects.py, find_a_supplier/tests/test_views.py
=> Fix engineering redirect

CHANGELOG.md, invest/templates/invest/landing_page.html
=> Added why choose uk button

CHANGELOG.md, investment_support_directory/templates/investment_support_directory/home.html
=> TT1752 - fix links  on homepage

CHANGELOG.md, conf/urls.py, contact/tests/test_views.py
=> Bug fix expand invest contact success

core/forms.py, core/templates/core/capital_invest/capital_invest_contact_form.html
=> Removed help text and heading from content comments

CHANGELOG.md, conf/urls.py
=> Fixed invest going to expand

core/templates/core/new_international_landing_page.html, core/tests/test_views.py, core/views.py
=> Fixes from better data - only show industries with description

CHANGELOG.md, core/views.py
=> Fix URLs for 'I want to Buy' on industry pages.

CHANGELOG.md, core/templates/core/landing_page.html
=> Added brexit banner to international home page

CHANGELOG.md, core/header_config/tier_two_nav_items.py
=> Change 'Professional Services' to 'Find a UK specialist'.

CHANGELOG.md, core/templates/core/about_uk/why_choose_the_uk_page.html
=> CI-498: Switch from pdf download to standard CTA.

CHANGELOG.md, core/templates/core/article_detail.html
=> Article tag removed hot fix

core/templatetags/cms_tags.py, core/tests/test_templatetags.py
=> Fix case where Hero Image is None.

CHANGELOG.md, core/templates/core/article_detail.html
=> Article hot fix

CHANGELOG.md, core/templatetags/cms_tags.py, makefile, perfect_fit_prospectus/templates/perfect_fit_prospectus/index.html, requirements.in, requirements.txt, requirements_test.txt
=> Fix hero IE bug

CHANGELOG.md, invest/templates/invest/landing_page.html
=> Fix broken invest hero text.

CHANGELOG.md, invest/templates/invest/landing_page.html
=> International Staging Bug fix

CHANGELOG.md, core/constants.py, core/header_config/nav_tree.py, core/header_config/tier_two_nav_items.py, requirements.in, requirements.txt, requirements_test.txt
=> Added how we help back into nav

CHANGELOG.md, core/templates/core/about_dit/services_page.html
=> Removed if statement so image isn't required for section

core/templates/core/about_dit/services_page.html
=> Change column width for intro

CHANGELOG.md, core/forms.py
=> Updated capital invest label on form triage

CHANGELOG.md, core/templates/core/landing_page.html
=> Hot fix add how we help back to home

CHANGELOG.md, core/templates/core/landing_page.html
=> Hot fix back into git flow

CHANGELOG.md, find_a_supplier/templates/find_a_supplier/contact.html, find_a_supplier/templates/find_a_supplier/landing_page.html
=> Added breadcrumbs to FAS overview page

CHANGELOG.md, core/constants.py, core/header_config/tier_one_nav_items.py, core/tests/test_helpers.py, requirements.in, requirements.txt, requirements_test.txt
=> Update directory constants

CHANGELOG.md, investment_support_directory/templates/investment_support_directory/home.html
=> Tt 1867 isd brokenlinks hotfix

investment_support_directory/templates/investment_support_directory/home.html
=> fix isd links

CHANGELOG.md, investment_support_directory/templates/investment_support_directory/home.html
=> Tt 2000 isd bad links hotfix

CHANGELOG.md, core/templates/core/uk_setup_guide/guide_landing_page.html, core/tests/test_templates.py
=> Show top 9 articles on guide/how to setup page

CHANGELOG.md, core/templates/core/article_detail.html, core/templates/core/article_related_content_list.html, core/tests/test_templates.py
=> Remove duplicated related content from article template

CHANGELOG.md, conf/settings.py, core/forms.py, euexit/forms.py, find_a_supplier/forms.py, find_a_supplier/tests/test_forms.py, investment_support_directory/forms.py, requirements.in, requirements.txt, requirements_test.txt
=> Fix missing logos in s3 bucket

CHANGELOG.md, core/fields.py, find_a_supplier/forms.py
=> hotfix Fix captcha on industry subscribe form

CHANGELOG.md, find_a_supplier/forms.py
=> Fix captcha on contact form

CHANGELOG.md, core/templates/core/landing_page.html
=> Remove padding on help section cards

CHANGELOG.md, contact/templates/contact/contact.html, locale/de/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/ja/LC_MESSAGES/django.po, locale/pt/LC_MESSAGES/django.po, locale/zh_Hans/LC_MESSAGES/django.po
=> Update form content

CHANGELOG.md, conftest.py, core/templatetags/cms_tags.py, core/tests/test_templatetags.py, find_a_supplier/templates/find_a_supplier/landing_page.html, find_a_supplier/tests/test_redirects.py, find_a_supplier/tests/test_templates.py, find_a_supplier/tests/test_views.py
=> Filter industries by language

CHANGELOG.md, core/constants.py, core/header_config/nav_tree.py, core/header_config/tier_one_nav_items.py, find_a_supplier/views.py
=> Switch header links order

CHANGELOG.md, core/templates/core/about_dit/about_dit_landing_page.html, core/templates/core/about_dit/services_page.html, core/templates/core/about_uk/about_uk_landing_page.html, core/templates/core/article_detail.html, core/templates/core/business_environment_guide_form.html, core/templates/core/business_environment_guide_form_success.html, core/templates/core/includes/cms_breadcrumbs.html, core/templates/core/topic_list.html, find_a_supplier/templates/find_a_supplier/case-study.html, find_a_supplier/templates/find_a_supplier/contact.html, find_a_supplier/templates/find_a_supplier/profile.html, find_a_supplier/templates/find_a_supplier/sent.html, invest/templates/invest/hpo/high_potential_opportunity_detail.html, investment_support_directory/templates/investment_support_directory/case-study.html, investment_support_directory/templates/investment_support_directory/contact.html, investment_support_directory/templates/investment_support_directory/profile.html
=> Fix broken breadcrumb

CHANGELOG.md, core/header_config/nav_tree.py
=> Change header links order under 'Expand'

CHANGELOG.md, core/templates/core/about_dit/services_page.html
=> Add ebook banner to about DIT services page

CHANGELOG.md, core/tests/test_views.py, core/views.py
=> Fix breadcrumb href

CHANGELOG.md, core/templates/core/about_dit/services_page.html
=> Fix empty href when no content on services page

CHANGELOG.md, core/forms.py
=> XOT-1253 add missing optional fields text

CHANGELOG.md, investment_support_directory/templates/investment_support_directory/search.html
=> TT2231 - isd filter orders

CHANGELOG.md, core/forms.py, core/templates/core/business_environment_guide_form.html, core/tests/test_forms.py, locale/de/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/ja/LC_MESSAGES/django.po, locale/pt/LC_MESSAGES/django.po, locale/zh_Hans/LC_MESSAGES/django.po
=> Update business environment guide form

CHANGELOG.md, conftest.py, contact/forms.py, contact/templates/contact/contact.html, contact/tests/test_forms.py, contact/tests/test_views.py, locale/de/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/ja/LC_MESSAGES/django.po, locale/pt/LC_MESSAGES/django.po, locale/zh_Hans/LC_MESSAGES/django.po
=> Ci 649 invest contact form

CHANGELOG.md, core/forms.py, core/templates/core/capital_invest/capital_invest_contact_form.html, core/tests/test_forms.py, core/tests/test_views.py
=> Update capital invest contact form

CHANGELOG.md, contact/forms.py, contact/templates/contact/contact.html, contact/tests/test_forms.py, contact/tests/test_views.py, locale/de/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/ja/LC_MESSAGES/django.po, locale/pt/LC_MESSAGES/django.po, locale/zh_Hans/LC_MESSAGES/django.po
=> Ci 649 invest contact updates

contact/forms.py, locale/de/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/ja/LC_MESSAGES/django.po, locale/pt/LC_MESSAGES/django.po, locale/zh_Hans/LC_MESSAGES/django.po
=> CI-649 missing select option

CHANGELOG.md, core/templates/core/why_buy_from_the_uk_form_success.html
=> XOT-1253 success page text change

CHANGELOG.md, core/header_config/nav_tree.py
=> Revert opportunities link in header

CHANGELOG.md, conf/tests/test_redirects.py, conf/url_redirects.py, conf/urls.py, euexit/tests/test_views.py
=> Change urls on brexit forms

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.txt
=> Bump waitress from 1.4.2 to 1.4.3 and django to 2.2.10

CHANGELOG.md, contact/templates/contact/contact.html, core/templates/core/companies/base-search.html, find_a_supplier/templates/find_a_supplier/buy_from_the_uk_form.html, invest/templates/invest/hpo/high_potential_opportunities_form.html, requirements.in, requirements.txt, requirements_test.txt
=> Cookie modal

requirements.in, requirements.txt, requirements_test.txt
=> Add mobile support to cookie modal

CHANGELOG.md, core/templates/core/capital_invest/capital_invest_opportunity_page.html, core/tests/test_views.py, core/views.py, locale/de/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/ja/LC_MESSAGES/django.po, locale/pt/LC_MESSAGES/django.po, locale/zh_Hans/LC_MESSAGES/django.po, makefile
=> Ci 614 fix related opportunities

CHANGELOG.md, core/tests/test_views.py, core/views.py, makefile
=> Why buy form privacy link

CHANGELOG.md, core/header_config/nav_tree.py
Reverts uktrade/great-international-ui#499
=> Revert "Revert opportunities link in header"

CHANGELOG.md, core/templates/core/capital_invest/capital_invest_opportunity_listing_page.html, locale/de/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/ja/LC_MESSAGES/django.po, locale/pt/LC_MESSAGES/django.po, locale/zh_Hans/LC_MESSAGES/django.po
- [ x ] Change has a jira ticket that has the correct status.
- [ x ] Changelog entry added.
- [ x ] (if changing content) Locale files have been updated and translated strings have been added if available.
=> CI-618 - opportunity listing no results wording

CHANGELOG.md, core/templates/core/capital_invest/capital_invest_opportunity_listing_page.html
- [ x ] Change has a jira ticket that has the correct status.
- [ x ] Changelog entry added.
- [  ] (if changing content) Locale files have been updated and translated strings have been added if available. (Not required)
=> CI-676 change wording of filter label

CHANGELOG.md, core/templates/core/landing_page.html
=> Get homepage urls from CMS

CHANGELOG.md, core/templates/core/about_uk/why_choose_the_uk_page.html
=> move prospectus up (below statistics) on 'why-choose-uk' page

CHANGELOG.md, core/constants.py, find_a_supplier/forms.py, find_a_supplier/tests/test_forms.py, investment_support_directory/forms.py, investment_support_directory/tests/test_views.py
=> Add marketing consent to forms

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.txt
- [Y] Changelog entry added.
- [Y] (if there are vulnerable requirements) Upgraded any vulnerable dependencies.
- [Y] (if updating requirements) Requirements have been compiled.
=> Hotfix_security_update_master

CHANGELOG.md, invest/templates/invest/hpo/high_potential_opportunity_detail.html
- [Y] Change has a jira ticket that has the correct status.
- [Y] Changelog entry added.
- [Y] (if adding HTML) Change is accessible to the standards we subscribe to.
- [Y] (if changing the UI) Add a printscreen to the PR
=> GAA-29_expander_link_using_GDS_pattern

CHANGELOG.md, core/templates/core/companies/base-search.html
=> GAA-6 - Find a UK supplier incorrect markup

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.txt
=> GAA-1, GAA-12 update directory components

CHANGELOG.md, core/templates/core/companies/base-search.html
=> TT-2373 fix search results

CHANGELOG.md, investment_support_directory/forms.py, requirements.in, requirements.txt, requirements_test.txt
=> GAA-8 Hidden label on search

CHANGELOG.md, core/templates/core/about_dit/services_page.html, core/templates/core/about_uk/about_uk_landing_page.html, core/templates/core/about_uk/why_choose_the_uk_page.html, core/templates/core/landing_page.html, core/templates/core/sector_page.html, requirements.in, requirements.txt, requirements_test.txt
=> GAA-23 - Fix blank headings issue

CHANGELOG.md, core/templates/core/companies/base-search.html, core/templates/core/includes/filter.html
=> GAA-7 Move aria expanded to button

core/templates/core/about_uk/why_choose_the_uk_page.html, core/templates/core/article_detail.html, core/templates/core/sector_page.html, invest/templates/invest/hpo/high_potential_opportunity_detail.html, requirements.in, requirements.txt, requirements_test.txt
=> Fix Alt text on various template

CHANGELOG.md, invest/templates/invest/hpo/high_potential_opportunities_form.html, invest/templates/invest/hpo/high_potential_opportunities_form_success.html, invest/templates/invest/hpo/high_potential_opportunity_detail.html
=> GAA-24 Added missing H1 for HPO template

CHANGELOG.md, core/templates/core/includes/form_consent.html, find_a_supplier/forms.py, find_a_supplier/tests/test_views.py, find_a_supplier/views.py
=> GAA-19-missing-privacy-link

CHANGELOG.md, core/templates/core/about_dit/services_page.html, core/templates/core/capital_invest/capital_invest_opportunity_page.html, core/templates/core/sector_page.html
=> GAA-26 - Add dark tint to case study backgrounds

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.txt
=> Version bump for directory-components

core/templates/core/capital_invest/capital_invest_contact_form.html
=> Fixed header tag

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.txt
=> GAA-9_Focus_trap_on_cookies_modal

CHANGELOG.md, find_a_supplier/templates/find_a_supplier/landing_page.html
=> Added empty alt tag

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.txt
=> Bump directory-components version

second_qualification/forms.py, second_qualification/tests/test_form.py
=> Default consent

CHANGELOG.md, find_a_supplier/forms.py
=> GBAU-77-Hotfix-captcha-on-form

CHANGELOG.md, find_a_supplier/forms.py
=>  GBAU-77-fix-hotfix-dev 

CHANGELOG.md, conftest.py, find_a_supplier/tests/test_views.py, find_a_supplier/views.py, investment_support_directory/tests/test_views.py, investment_support_directory/views.py
=> fix search for ES upgrade

CHANGELOG.md, contact/templates/contact/contact.html, core/templates/core/capital_invest/capital_invest_contact_form.html, core/templates/core/companies/base-contact.html, core/templates/core/why_buy_from_the_uk_form.html, euexit/templates/euexit/form-contents.html, find_a_supplier/templates/find_a_supplier/buy_from_the_uk_form.html, invest/templates/invest/hpo/high_potential_opportunities_form.html, perfect_fit_prospectus/templates/perfect_fit_prospectus/index.html
=> Added autocompelete attributes to forms

CHANGELOG.md, euexit/templates/euexit/form-contents.html
=> hotfix transition form

CHANGELOG.md, euexit/templates/euexit/form-contents.html
=> apply-hotfix-to-dev

CHANGELOG.md, perfect_fit_prospectus/forms.py, perfect_fit_prospectus/templates/perfect_fit_prospectus/index.html, perfect_fit_prospectus/tests/test_views.py
Adds accessible version option to perfect fit form.
=> adds an option to request an accessible text only report

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.txt
=> Django upgrade

CHANGELOG.md
=> Post release 2.0.0 CL update

CHANGELOG.md, investment_support_directory/templates/investment_support_directory/home.html
Content update for BAU International site
=> updated content for investment support directory

.circleci/config.yml, CHANGELOG.md, README.md, conf/settings.py, investment_support_directory/templates/investment_support_directory/home.html, manifest.yml, requirements.in, requirements.txt, requirements_test.in, requirements_test.txt, runtime.txt
=> staging release

CHANGELOG.md, core/templates/core/companies/base-search.html
=> GP2-2873 - XSS defence - force escape search query

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.txt
=> GP2-2711: Bump directory-components

CHANGELOG.md, investment_atlas/templates/investment_atlas/includes/related_opportunities.html, investment_atlas/templates/investment_atlas/opportunity.html
(The CMS change is clearer and faster for editors to work with - see https://github.com/uktrade/directory-cms/pull/914 )
=> GP2-3392: Refactor Opportunity page to use specific intro and hero images

CHANGELOG.md, core/constants.py, invest/templates/invest/why_invest_in_the_uk_page.html
=> Added WhyInvestInTheUK Page

CHANGELOG.md, core/header_config/nav_tree.py, core/header_config/tier_two_nav_items.py
=> NOTICKET: change Investment sub-menu to feature sectors not industries

CHANGELOG.md, investment_atlas/templates/investment_atlas/includes/speak_to_us.html
=> NOTICKET - Amend phrasing in Speak To Us panel

CHANGELOG.md, core/constants.py, core/header_config/nav_tree.py, core/header_config/tier_two_nav_items.py, investment_atlas/templates/investment_atlas/general_content_page.html
Also adds a nav element and an appropriate 'active' state
Builds on the backend provided by https://github.com/uktrade/directory-cms/pull/923
=> GP2-3400: Template for generic atlas content page, which can be used for new How We Can Help page

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.txt
=> d-component version bump for cookie modal fix

CHANGELOG.md, core/header_config/tier_two_nav_items.py, investment_atlas/templates/investment_atlas/opportunity_listing_page.html
=> GP2-348: Regions name changes to UK Nations and Regions

core/constants.py
=> GP2-3407: fix incorrect template mapping

CHANGELOG.md, core/header_config/tier_two_nav_items.py, investment_atlas/templates/investment_atlas/opportunity_listing_page.html
=> NOTICKET: Capitalisation/phrasing fixups re UK region and nation labelling

CHANGELOG.md, conf/settings.py, contact/tests/test_views.py, core/tests/test_helpers.py, core/views.py
=> Disabling translation for site

CHANGELOG.md, conf/tests/test_redirects.py, conf/tests/test_urls.py, conf/url_redirects.py, conf/urls.py, core/tests/test_views.py, invest/tests/test_views.py
=> Gp2 3269  redirects for retired pages

core/templates/core/base.html, investment_atlas/templates/investment_atlas/base_cms.html, investment_atlas/templates/investment_atlas/homepage.html, investment_atlas/templates/investment_atlas/investment.html, investment_atlas/templates/investment_atlas/opportunity_listing_page.html, investment_atlas/templates/investment_atlas/why_invest_in_the_uk_page.html
- Increase spacing below "Why invest in the UK" cards in main content
- Increase heading size on Opportunities listing page
- Decrease spacing below heading on Opportunities listing page
- Fix main menu button not working on legacy pages (contact us/find a supplier/etc)
=> NOTICKET Snags list 3

investment_atlas/templates/investment_atlas/opportunity_listing_page.html, investment_atlas/tests/test_views.py, investment_atlas/views.py
- Prevent error when viewing map with no results
- Tweak layout and content when no results, add link to clear all filters
=> GP2-3669 Opportunities map tweaks and fixes

investment_atlas/templates/investment_atlas/includes/hero_image.html
Prevents a 404 if no video thumbnail available.
=> NOTICKET Prevent 404 if no thumbnail

.circleci/config.yml, conf/tests/test_redirects.py, conf/url_redirects.py
This changeset fix if someone tries to visit URL with an extra backslash
=> Redirect fix

package-lock.json, package.json
Fix `trim-newlines` and `nth-check` vulnerabilities.
Superseded #781 
=> CHORE: vulnerabilities 2021 11 02

conf/url_redirects.py, conf/urls.py, core/templates/core/capital_invest/capital_invest_contact_form.html, core/tests/test_views.py, core/views.py
=> Moving invest capital form into Atlas

requirements.in, requirements.txt, requirements_test.txt
Fixes `pillow` vulnerability.
Supersedes #794
=> Upgrade pillow

CHANGELOG.md, conf/tests/test_redirects.py, conf/url_redirects.py
=> GLS-78 Add redirect for unlinked Opportunities listing page type URL

package-lock.json, package.json, webpack.config.js
=> NOTICKET Generate sourcemaps for CSS files

CHANGELOG.md, package-lock.json
package-lock.json update to fix deep dependency vulnerability.
=> GLS-157 fix minimist vulnerability

CHANGELOG.md, investment_atlas/templates/investment_atlas/opportunity_listing_page.html
In case a lat/long has been entered incorrectly in d-cms, this prevents the processing of all the markers from stoping and outputs a small error message to the console pointing to opportunity with the incorrect data.
=> GLS-193 - Handle invalid lat/long gracefully

.circleci/config.yml, CHANGELOG.md, package-lock.json, package.json
Update node engine specification to v16 (v12 is no longer marked as supported/stable: https://nodejs.org/en/about/releases/).
=> CHORE Update node engine

CHANGELOG.md, package-lock.json, package.json
This fixes https://github.com/uktrade/great-international-ui/security/dependabot/33.
=> GLS-255 fix semver-regex vulnerability

CHANGELOG.md
=> Post-release changelog update - 3.6.1

CHANGELOG.md, README.md, development.yml, dockerise/postgres/init-db.sh, makefile
Streamline Docker start by adding `directory-api` and OpenSearch containers to enable 'Find a supplier'. Update README accordingly to include steps to seed test search data.
=> GLS-254 update docs

CHANGELOG.md, investment_support_directory/templates/investment_support_directory/home.html
=> Remove content from Investment Support Directory

CHANGELOG.md
Update changelog for release 3.7.0.
=> Post-release changelog update for 3.7.0

CHANGELOG.md
Post-release entry to changelog for release 3.7.1
=> Post release changelog entry for 3.7.1

CHANGELOG.md, investment_support_directory/templates/investment_support_directory/home.html
This PR adds text containing a disclaimer to the investment support directory page.
**Screenshot**
=> Add disclaimer to investment support directory

CHANGELOG.md
This PR updates the Changelog following release 3.8.0.
=> Post-release changelog update - 3.8.0

requirements.in, requirements.txt, requirements_test.txt
=> Upgrade django-redis to be compataile with Django 3.2

CHANGELOG.md
Merge the release branch into the develop branch to resolve conflicts.
=> Merge release branch into develop

CHANGELOG.md
This PR updates the changelog following release 3.9.1
=> Post-release changelog update - 3.9.1

CHANGELOG.md
Update the changelog following release 3.9.2.
=> Post-release changelog update - 3.9.2

pull_request_template.md
Update PR template with list of internal dependencies.
=> Add internal dependencies to PR template

jest.config.js, package-lock.json, package.json
Jest introduced word-wrap so updating it addressed the vulnerability
=> KLS-824 Upgrade for word-wrap - great-international-ui

requirements.in, requirements.txt, requirements_test.txt
=> Kls 1307 pillow upgrade

requirements.in, requirements.txt, requirements_test.txt
=> Release 4.2.13

manifest.yml, requirements.txt, requirements_test.txt
=> Cflinux4 update

manifest.yml
add back stack defn to manifest
=> add back stack defn to manifest

requirements.in, requirements.txt, requirements_test.txt
=> Upgrade Django to 4.2

investment_atlas/templates/investment_atlas/includes/svg/icon-arrow.svg
Adjusts chevron colour to improve colour contrast
=> KLS-1414: Improve chevron color contrast

requirements.in, requirements.txt, requirements_test.txt
(Please add a sentence or two explaining the context of this PR. Reviewers can go to the ticket for detail.)
CONTEXT: This changeset adds/removes/updates [summary of feature/area/code] so that [summary of benefit].
_Tick or delete as appropriate:_
=> Bump version of directory components dependency 

find_a_supplier/views.py
Check weather url is safe before redirection . 
_Tick or delete as appropriate:_
=> KLS-1918: Update URL redirection and check safe url

core/templates/atlas/components/header.html
PR to add data-location and data-title attributes to primary and sub navigation to assist with tracking user journeys.
=> IOO-1175 add data tagging to nav items

core/templates/atlas/components/footer.html
Ioo 1198 contact params next url pass to great cms international contact page to ensure back and continue links resume users previous journey prior to contacting us.
_Tick or delete as appropriate:_
N/A
=> Ioo 1198 contact params next url

requirements.in, requirements.txt, requirements_test.txt
=> Bump idna to 3.7

requirements.in, requirements.txt, requirements_test.txt
=> Bump gunicorn to 22.0.0

core/templates/core/base.html
Added a new canonical tag as it was missing.
=> New canonical link added to head_other block

package-lock.json, package.json
=> Bump up ws & braces

core/templates/core/base.html, core/templatetags/canonical_url_tags.py, core/tests/test_templatetags.py, core/utils.py, requirements.txt, requirements_test.txt
=> Correct canonical url 

core/templatetags/canonical_url_tags.py, core/tests/test_templatetags.py
find a supplier canonical url - address special cases
=> find a supplier canonical url - address special cases

core/header_config/tier_one_nav_items.py, core/header_config/tier_two_nav_items.py
Updating urls in header to point at great-cms hosted buy-from-the-uk index
N/A
=> Updating urls in header to point at great-cms hosted buy-from-the-uk index

core/header_config/tier_two_nav_items.py
Pointing nav item for buy from the uk contact at great-cms buy from the uk contact
N/A
=> Pointing nav item for buy from the uk contact at great-cms buy from the uk contact

core/templates/core/base.html
This ticket add hreflang tags to the pages of International UI.
=> Add hreflang tags

core/header_config/tier_two_nav_items.py, core/templates/core/base.html
=> Release PR

core/header_config/tier_two_nav_items.py, core/templates/core/base.html
=> UAT / PROD release

core/templates/core/base.html, core/templates/core/base_cms.html, core/templatetags/canonical_url_tags.py, core/tests/test_templatetags.py, core/utils.py, requirements.txt, requirements_test.txt
Add hreflang and x-default links where appropriate
=> Add hreflang and x-default links where appropriate
